### ISSUE TITLE
Is this project alive any more? I have a need for a monitor.

### ISSUE THREAD

**Issue by Cingulara** [oci-labs/opendds-web-monitor#14]
Is this a working project? Do you need or want help in getting pieces done? I have a need for this on a project and would love to see what you were trying to do, how to get the statistics, setup variables for where to connect to OpenDDS, etc.

**Comment by mitza-oci** [comment]
We are not actively developing it at this time due to other priorities.

All the code is (obviously) available, and there is a "project" in GitHub that describes some next steps that could be taken.  But of course that will depend on your own requirements.
